### ISSUE TITLE
why is "error: fatal" message not managed?

### ISSUE THREAD

**Issue by jgyy** [shackbei/microshell-42#16]
If a system call, except execve and chdir, returns an error your program should immediatly print "error: fatal" in STDERR followed by a '\n' and the program should exit.

The text above is one of the exam criteria, why is this error message not being managed inside the provided solutions?
 
For example if pipe, fork, dup, dup2 command returns -1, the system should print out "error: fatal\n" to stderr.

**Comment by shackbei** [comment]
This is a bad practice exam solution.
But with few lines of code.
You are absolutely right but it seems to work without it.

**Comment by jgyy** [comment]
Realistically speaking the chances of system function failing such as dup dup2 fork pipe and even malloc is very minute, its just a personal fear that when the exam question explicitly stated for it and not provided, they will mark the answer as wrong.

Anyway thanks a lot for sharing your solution though.
