### ISSUE TITLE
Time Out

### ISSUE THREAD

**Issue by Marvyn42** [shackbei/microshell-42#6]
J'ai eu un time out lors de l'exam. La commande du test 8 était une succession de pleins de commandes avec des pipes. Je n'ai pas réussi à savoir pour quelle raison le programme a time out.

**Comment by yavuzsonmez** [comment]
shakbei ne parle pas français.
Time out avec grademe ou avec le tester? Linux ou MacOS?

**Comment by Marvyn42** [comment]
Ah mince, désolé.
Time out sur grademe, c'était du linux

Le ven. 6 mai 2022 à 10:04, Yavuz Sönmez ***@***.***> a
écrit :

**Comment by Marvyn42** [comment]
ended
